#!/bin/sh

LLVM_VERSION=${1:-7}
BPFTRACE_PATH=${BPFTRACE_PATH:-$(git rev-parse --show-toplevel 2>/dev/null)}

if test -z "$BPFTRACE_PATH"; then
  echo "BPFTRACE_PATH not set and couldn't guess it";
  exit 1;
fi

DIR="$(dirname "$(readlink -f "$0")")"

make -s -C $DIR run-$LLVM_VERSION BPFTRACE_PATH=$BPFTRACE_PATH
